version: "3.7"

services:

  veselkaback:
    # build: .
    image: mobius7/v_back_image:latest
    environment:
      REDIS_HOST: "$REDIS_HOST"
      REDIS_PORT: "$REDIS_PORT"
      REDIS_PASSWORD: "$REDIS_PASSWORD"
      API_URL: "$API_URL"
      BOT_URL: "$BOT_URL"
      API_USERNAME: "$API_USERNAME"
      API_PASSWORD: "$API_PASSWORD"
      API_INSTALLID: "$API_INSTALLID"
      COREZOID_SECRET_KEY: "$COREZOID_SECRET_KEY"
      COREZOID_LOGIN : "$COREZOID_LOGIN"
      COREZOID_PROCCESS_ID : "$COREZOID_PROCCESS_ID"
      ENV_NAME: "$ENV_NAME"      

    ports:
      - "$DOCKER_PORT:8000"
    # volumes:
    #   - "./:/code"
    depends_on:
      - "redis"

  redis:
    image: redis
    command: ["redis-server",  "--requirepass", "$REDIS_PASSWORD"]
    # ports:
    #   - "16379:6379"